version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/back-end"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
