# Enforce padrão de commits semânticos
titleOnly: false
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - test
  - chore
scopes:
  - front-end
  - back-end
  - ci
  - build
  - deps  
  - documentacao
  - api

  