services:
  front-end:
    build: ./front-end
    container_name: imobiliario-frontend
    ports:
      - "3000:3000"
    
    depends_on:
      - back-end

  back-end:
    build: ./back-end
    container_name: imobiliario-backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
