services:
  front-end:
    build: ./front-end
    container_name: ${DOCKER_HUB_USERNAME}/imobiliario-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - back-end

  back-end:
    build: ./back-end
    container_name: ${DOCKER_HUB_USERNAME}/imobiliario-backend:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
