site_name: Imobiliaria Bortone - Documentação

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.details


theme:
  name: material
  language: pt
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  palette:
    - scheme: default
      primary: custom
      accent: indigo
  feature:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
extra_css:
  - stylesheets/custom.css

nav:
  - Início: index.md
  - Regras Gerais do Repositório: RegrasGerais.md
  - Estrutura de Pastas: EstruturaDePastas.md
  - Configurações do Next: frontend/NextConfig.md
  - Middleware: frontend/middlwareIndexacao.md
  - Manual de Tags: frontend/ManualdeTags.md
  - Algoritmo de Recomendação: api/AlgoritmoDeRecomendacao.md
  - Banco de Dados: api/BancoDeDados.md
  - Dashboard: api/dashboard.md
  - API de Mapa: api/MapaAPI.md
  - Implementação da API de Mapa: api/MapaImplementacao.md
  - Resumo da Integração: api/MapaResumo.md
  - Chat Suporte: api/ChatSuporte.md

  
