name: Build and Push Docker Images via Compose 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and push images

        run: docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml push
        
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
          DB_DATABASE: ${{secrets.DB_DATABASE}}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}
          SMTP_HOST: ${secrets.SMTP_HOST}
          SMTP_SECURE: ${secrets.SMTP_SECURE}
          SMTP_USER: ${secrets.SMTP_USER}
          SMTP_PASS: ${secrets.SMTP_PASS}
          SMTP_HELO: ${secrets.SMTP_HELO}
          MAIL_FROM_EMPRESA: ${secrets.MAIL_FROM_EMPRESA}
          MAIL_TO_EMPRESA: ${secrets.MAIL_TO_EMPRESA}


