name: Keep Render Awake
 
on: 
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:
 
jobs:
  ping:
    runs-on: ubuntu-latest
    steps: 
      - name: Request API
        id: call_api
        run: |
          RESPONSE=$(curl -s -w " [status:%{http_code} tempo:%{time_total}s]" -o response.txt https://imobiliaria-bortone.onrender.com/health)
          CONTENT="$(cat response.txt)$RESPONSE"
          echo "response=$RESPONSE" >> $GITHUB_ENV
 
      - name: Send to Discord
        run: |
          PAYLOAD=$( echo "$CONTENT" | jq -Rs .)
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": $PAYLOAD}"\
          "${{ secrets.DISCORD_WEBHOOK }}"
